name: example-servant-persistent
version: "0.1.0.0"
synopsis: example with persistent and servant
description: Simple example to illustrate how to use persistent and servant in combination.
category: Web
author:
  - orehathiya
maintainer:
  - merrynewyear6593@gmail.com
license: BSD3
ghc-options: -Wall
dependencies:
  - base >=4.8 && <5
  - aeson
  - basement
  - bytestring
  - dhall
  - http-types
  - lens
  - monad-logger
  - mtl
  - resourcet
  - persistent
  - persistent-template
  - persistent-sqlite
  - servant
  - servant-client
  - servant-docs
  - servant-server
  - string-conversions
  - text
  - time
  - transformers
  - wai
  - swagger2
  - warp
  - yaml

library:
  source-dirs: lib

executables:
  example-servant-persistent:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - example-servant-persistent
      - wai-cors
  example-servant-persistent-doc:
    main: Doc.hs
    source-dirs:
      - doc
    dependencies:
      - example-servant-persistent
      - aeson-pretty
  example-servant-persistent-swagger:
    main: Swagger.hs
    source-dirs:
      - swagger
    dependencies:
      - example-servant-persistent
      - servant-swagger
      - aeson-pretty
  psGenerator:
    main: PSGenerator.hs
    source-dirs:
      - gen
    dependencies:
      - example-servant-persistent
      - containers
      - filepath
      - http-api-data
      - mainland-pretty
      - purescript-bridge
      - servant-foreign
      - servant-purescript
      - servant-subscriber
tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - example-servant-persistent
      - hspec
      - exceptions
      - http-client
      - http-media
      - mockery
