resolver: lts-10.0
packages:
  - '.'
extra-deps:
  - datetime-0.3.1
docker:
  enable: true

image:
  containers:
    -
      base: "fpco/ubuntu-with-libgmp:14.04"
      add:
        config/: /config/
      entrypoints:
        - example-servant-persistent
